### PR TITLE
Replace expanduser with shellexpand

### LINKED ISSUE #402: Package support breaks candy on Windows
**Describe the bug**
#390 introduced a bug where the module resolution inside packages fails to detect if a file is located in the package on Windows. 

The underlying problem is the platform specific behavior of `fs::canonicalize` (see [the documentation](https://dev-doc.rust-lang.org/beta/std/fs/fn.canonicalize.html#platform-specific-behavior)). This function returns a UNC-Path prefixed with `\\?\` while `package.to_path` returns a DOS-Path without the prefix. `strip_prefix` then returns an error and the compiler thinks the file is not located in the package.

The [dunce crate](https://lib.rs/crates/dunce) was created to combat this issue, but converting the UNC-path to a URL and back to a file path seems to be a quick workaround.

```rust
let canonicalized = Url::from_file_path(canonicalized)
    .expect("Invalid file path.")
    .to_file_path()
    .expect("File path conversion error.");
```

### PR DESCRIPTION
**Pull request by skyz1**
Closes: #402 

This PR replaces the `expanduser` crate added in #412 with `shellexpand`, since `expanduser` doesn't compile on windows.

However `shellexpand` doesn't expand `~user` with the home directory of `user`. If this leads to problems, conditional compilation could be used in the future to bring that feature back in.

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: compiler/frontend/src/module/package.rs [hunk 1]
```diff
@@ -59,9 +59,7 @@ impl TryFrom<&str> for PackagesPath {
     type Error = String;
 
     fn try_from(path: &str) -> Result<Self, Self::Error> {
-        expanduser(path)
-            .map_err(|it| it.to_string())
-            .and_then(|it| it.as_path().try_into())
+        PathBuf::from(tilde(path).to_string()).as_path().try_into()
```
Comment (JonasWanke) [inline compiler/frontend/src/module/package.rs]: We can avoid the allocation behind `to_string()`, the borrowed `Path` suffices:

```suggestion
        Path::new(tilde(path).as_ref()).try_into()
```

**Review by JonasWanke — CHANGES_REQUESTED** [review]

**Review by JonasWanke — APPROVED** [review]
