### PR TITLE
Fix text with leading whitespace parsing

### LINKED ISSUE #896: Text literal is missing whitespace after opening quote
**Describe the bug**

`" abcdefg "` gets parsed to the text `"abcdefg "`

### PR DESCRIPTION
**Pull request by styrix560**
Closes: #896

### Checklist

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: compiler/vm/src/heap/mod.rs [hunk 1]
```diff
@@ -199,6 +199,7 @@ impl Default for Heap {
 
 impl Drop for Heap {
     fn drop(&mut self) {
+        println!("{:?}", self.objects);
```
Comment (JonasWanke) [inline compiler/vm/src/heap/mod.rs]:
```suggestion
```

File: compiler/frontend/src/string_to_rcst/text.rs [hunk 2]
```diff
@@ -16,8 +16,17 @@ use tracing::instrument;
 pub fn text(input: &str, indentation: usize) -> Option<(&str, Rcst)> {
     let (input, opening_single_quotes) = parse_multiple(input, single_quote, None)?;
     let (mut input, opening_double_quote) = double_quote(input)?;
-    let (new_input, opening_whitespace) = whitespaces_and_newlines(input, indentation + 1, false);
-    input = new_input;
+    let (new_input, mut opening_whitespace) =
+        whitespaces_and_newlines(input, indentation + 1, false);
+
```
Comment (JonasWanke) [inline compiler/frontend/src/string_to_rcst/text.rs:22]: I'd move the blank line above because this and the `if`/`else` below belong together

```suggestion

    let (new_input, mut opening_whitespace) =
        whitespaces_and_newlines(input, indentation + 1, false);
```

File: compiler/frontend/src/string_to_rcst/text.rs [hunk 3]
```diff
@@ -16,8 +16,17 @@ use tracing::instrument;
...
+    // if the string does not contain any newlines, parse the whitespace in
+    // front of the string as part of the string and not as trailing whitespace
+    // this fixes issue #896
```
Comment (JonasWanke) [inline compiler/frontend/src/string_to_rcst/text.rs]:
```suggestion
    // If the string does not contain any newlines, parse the whitespace in
    // front of the string as part of the string and not as trailing whitespace.
    // This fixes https://github.com/candy-lang/candy/issues/896.
```

**Review by JonasWanke — CHANGES_REQUESTED** [review]

**Comment by styrix560** [comment]
I messed up with the merge. I will fix this and request another review

**Review by JonasWanke — APPROVED** [review]
